 
services:
 db:
  ports: 
    - 5432:5432
  container_name: postgresql_container
  image: postgres
  environment:
   - POSTGRES_DB=postgres
   - POSTGRES_PASSWORD=123456
   - POSTGRES_USER=postgres
  restart: always 
 backend:
  build: .
  container_name: springboot-servicio-libros_container
  ports:
  - 8081:8001
  environment:
   db-url: r2dbc:postgresql://db:5432/postgres
   db-username: postgres
   db-password: 123456
  depends_on:
  - db
  restart: always
